# Generated by Django 4.0.2 on 2022-07-17 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_alter_todo_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='info',
            field=models.TextField(blank=True),
        ),
    ]
