# Generated by Django 4.0.2 on 2022-07-20 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_status_todo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0, unique=True),
        ),
    ]
