# Generated by Django 4.0.2 on 2022-07-20 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_status_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='status',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
