# Generated by Django 4.0.2 on 2022-07-20 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0007_todo_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='date_created',
            new_name='complete_by',
        ),
    ]
