# Generated by Django 4.0.2 on 2022-07-20 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0008_rename_date_created_todo_complete_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='complete_by',
            new_name='date_created',
        ),
    ]
