# Generated by Django 4.0.2 on 2022-07-20 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0009_rename_complete_by_todo_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='deadline',
            new_name='complete_by',
        ),
    ]
