# Generated by Django 4.0.2 on 2022-07-20 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0010_rename_deadline_todo_complete_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='complete_by',
        ),
        migrations.AddField(
            model_name='todo',
            name='complete_by_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
